# Generated by Django 4.1 on 2022-11-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Students Full Name"),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman - (9th Grade)"),
                            ("SO", "Sophomore - (10th Grade)"),
                            ("JR", "Junior - (11th Grade)"),
                            ("SR", "Senior - (12th Grade)"),
                            ("GR", "College"),
                        ],
                        default="JR",
                        max_length=2,
                        verbose_name="Grade Level",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=1500,
                        null=True,
                        verbose_name="Additional Information",
                    ),
                ),
                ("creation_date", models.DateField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject",
                        to="tutoring.subject",
                        to_field="subject_name",
                        verbose_name="Subject",
                    ),
                ),
            ],
        ),
    ]
